with reviews as (

    select * from {{ ref('dim_review') }}

),

split_temp as (

    select 
        coffee_id,
        tasting_notes
    from reviews,
         UNNEST(SPLIT(LOWER(tasting_notes))) as tasting_notes
         with OFFSET AS offset
         order by offset

),

taste as (

    select
        coffee_id,
        tasting_notes,
        CASE
             WHEN CONTAINS_SUBSTR(tasting_notes , 'blackberry') THEN 'blackberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mulberry') THEN 'mulberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'boysenberry') THEN 'boysenberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'elderberry') THEN 'elderberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'raspberry') THEN 'raspberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'blueberry') THEN 'blueberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'gooseberry') THEN 'gooseberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'strawberry') THEN 'strawberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cranberry') THEN 'cranberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'goji') THEN 'goji berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'currant') THEN 'currant'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'berry') THEN 'other berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'berries') THEN 'other berry'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'raisin') THEN 'raisin'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'golden raisin') THEN 'golden_raisin'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'prune') THEN 'prune'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dried plum') THEN 'prune'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'date') THEN 'date'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'coconut') THEN 'coconut'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cherry') THEN 'cherry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pomegranate') THEN 'pomegranate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pinapple') THEN 'pinapple'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grape') THEN 'grape'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'apple') THEN 'apple'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'peach') THEN 'peach'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pear') THEN 'pear'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'banana') THEN 'banana'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'juicy') THEN 'juicy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'juniper') THEN 'juniper'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'persimmon') THEN 'persimmon'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'apricot') THEN 'apricot'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'plum') THEN 'plum'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fig') THEN 'fig'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pluot') THEN 'pluot'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tamarind') THEN 'tamarind'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rhubarb') THEN 'rhubarb'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tomato') THEN 'tomato'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'guava') THEN 'guava'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'papaya') THEN 'papaya'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lychee') THEN 'lychee'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'passion') THEN 'passion fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'starfruit') THEN 'star fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mango') THEN 'mango'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'melon') THEN 'melon'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cantaloupe') THEN 'cantaloupe'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'honeydew') THEN 'honeydew'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'breadfruit') THEN 'breadfruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'loquat') THEN 'loquat'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruit') THEN 'fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruit-toned') THEN 'fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruit-forward') THEN 'fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruity') THEN 'fruit'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'lemon') THEN 'lemon'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grapefruit') THEN 'grapefruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pomelo') THEN 'pomelo'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'orange') THEN 'orange'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bergamot') THEN 'bergamot'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tangerine') THEN 'tangerine'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nectarine') THEN 'nectarine'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mandarin') THEN 'mandarin'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'kumquat') THEN 'kumquat'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lime') THEN 'lime'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'yuzu') THEN 'yuzu'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sumac') THEN 'sumac'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'citrus') THEN 'citrus'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'clementine') THEN 'clementine'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'quince') THEN 'quince'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'rum') THEN 'rum'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grappa') THEN 'grappa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'brandy') THEN 'brandy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cognac') THEN 'cognac'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'whiskey') THEN 'whiskey'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wine') THEN 'wine'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'yogurt') THEN 'yogurt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'milk') THEN 'milk'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cheese') THEN 'cheese'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pinot noir') THEN 'wine'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bourbon') THEN 'bourbon'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tequila') THEN 'tequila'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fraamboise') THEN 'framboise'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'contreau') THEN 'contreau'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'liqueur') THEN 'liqueur'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ferment') THEN 'ferment'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'overripe') THEN 'overripe'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'alcohol') THEN 'alcohol'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'olive oil') THEN 'olive oil'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'raw') THEN 'raw'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'under-ripe') THEN 'under-ripe'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'peapod') THEN 'peapod'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fresh') THEN 'fresh'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dark green') THEN 'dark green'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vegetable') THEN 'vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vegetative') THEN 'vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hay') THEN 'hay-like'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'herb') THEN 'herb-like'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bean') THEN 'beany'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mint') THEN 'mint'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'parsely') THEN 'parsely'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grass') THEN 'grass'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hop') THEN 'hop'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bay leaf') THEN 'bay leaf'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'thyme') THEN 'thyme'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ginseng') THEN 'ginseng'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ginger') THEN 'ginger'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'marjoram') THEN 'marjoram'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tarragon') THEN 'tarragon'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sarsaparilla') THEN 'sarsaparilla'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'frankincense') THEN 'frankincense'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'frankinense') THEN 'frankincense'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'oregano') THEN 'oregano'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fennel') THEN 'fennel'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cilantro') THEN 'cilantro'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dill') THEN 'dill'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'herb') THEN 'herb-like'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'turmeric') THEN 'turmeric'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'malt') THEN 'malt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cereal') THEN 'cereal'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grain') THEN 'grain'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'graham cracker') THEN 'grain'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rice') THEN 'rice'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sage') THEN 'pungent'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pungent') THEN 'pungent'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pepper') THEN 'pepper'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'anise') THEN 'anise'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nutmeg') THEN 'nutmeg'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mace') THEN 'mace'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cinammon') THEN 'cinammon'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cinnamon') THEN 'cinammon'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'clove') THEN 'clove'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cardamom') THEN 'cardamom'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'myrrh') THEN 'myrrh'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'coriander') THEN 'coriander'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cumin') THEN 'cumin'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mustard') THEN 'mustard'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cayenne') THEN 'cayenne'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cellery seed') THEN 'cellery seed'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'paprika') THEN 'paprika'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'saffron') THEN 'saffron'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'spicy') THEN 'spicy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'spice') THEN 'spice'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'peanuts') THEN 'peanuts'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hazelnut') THEN 'hazelnut'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'almond') THEN 'almond'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pistachio') THEN 'pistachio'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cashew') THEN 'cashew'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pecan') THEN 'pecan'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'frangipane') THEN 'frangipane'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'marzipan') THEN 'marzipan'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'macadamia') THEN 'macadamia'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hempseed') THEN 'hempseed'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'taro') THEN 'taro'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nut') THEN 'nutty'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'dark chocolate') THEN 'dark chocolate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chocolate') THEN 'chocolate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chocolaty') THEN 'chocolate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cocoa') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cacao') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cocoo') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cocao') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'carob') THEN 'carob'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tiramisu') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fudge') THEN 'chocolate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'oreo') THEN 'chocolate'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'molasses') THEN 'molasses'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'toffee') THEN 'caramel'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'maple syrup') THEN 'maple syrup'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'caramel') THEN 'caramelized'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'butterscotch') THEN 'butterscotch'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'brown sugar') THEN 'brown sugar'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'creme brulee') THEN 'creme brulee'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'agave') THEN 'agave'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'honey') THEN 'honey'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vanilla') THEN 'vanilla'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vanillin') THEN 'vanillin'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sweet aromatics') THEN 'sweet aromatics'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'jolly rancher') THEN 'jolly rancher'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bubblegum') THEN 'bubble gum'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cream') THEN 'cream'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nougat') THEN 'nougat'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'halvah') THEN 'halvah'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'praline') THEN 'praline'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'candy') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'taffy') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'marshmallow') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sugar') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sweet') THEN 'overall sweet'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'sour') THEN 'sour'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'acid') THEN 'sour'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bright') THEN 'sour'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'crisp') THEN 'sour'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'black tea') THEN 'black tea'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chamomile') THEN 'chamomile'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rose') THEN 'rose'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'jasmine') THEN 'jasmine'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'gardenia') THEN 'gardenia'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'freesia') THEN 'freesia'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'magnolia') THEN 'magnolia'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'honeysuckle') THEN 'honeysuckle'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wisteria') THEN 'wisteria'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'verbena') THEN 'verbena'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lily') THEN 'lily'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nasturtium') THEN 'nasturtium'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lilac') THEN 'lilac'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'carnation') THEN 'carnation'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'narcissus') THEN 'narcissus'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'blossom') THEN 'blossom'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'violet') THEN 'violet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rhododendron') THEN 'rhododendron'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hibiscus') THEN 'hibiscus'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tea') THEN 'tea'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wisteria') THEN 'wisteria'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'orchid') THEN 'orchid'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lantana') THEN 'lantana'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'alyssum') THEN 'alyssum'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lavender') THEN 'lavender'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'perfumed') THEN 'perfumed'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hyacinth') THEN 'hyacinth'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'azalea') THEN 'azalea'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'osmanthus') THEN 'osmanthus'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chrysanthemum') THEN 'chrysanthemum'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'floral') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'flower') THEN 'floral'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'bitter') THEN 'bitter'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'salty') THEN 'salty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'medicinal') THEN 'medicinal'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'petroleum') THEN 'petroleum'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'skunky') THEN 'skunky'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rubber') THEN 'rubber'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'pipe tobacco') THEN 'pipe tobacco'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tobacco') THEN 'tobacco'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'acrid') THEN 'acrid'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'burnt') THEN 'ashy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ash') THEN 'ashy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'scorched') THEN 'ashy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'smoky') THEN 'smoky'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'toasted') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'roast-toned') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'roast-prominent') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'leather') THEN 'leather'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'teriyaki sauce') THEN 'teriyaki sauce'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tamari') THEN 'tamari'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bold') THEN 'bold'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'stale') THEN 'stale'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cardboard') THEN 'cardboard'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'paper') THEN 'papery'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cedar') THEN 'cedar'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wood') THEN 'wood'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'oak') THEN 'oak'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fir') THEN 'fir'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mesquite') THEN 'mesquite'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'elm') THEN 'elm'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sassafras') THEN 'sassafras'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'balsa') THEN 'balsa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'barley') THEN 'barley'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bay tree') THEN 'bay'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pine') THEN 'pine'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'eucalyptus') THEN 'eucalyptus'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'palo santo') THEN 'palo santo'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'moist') THEN 'moist'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mold') THEN 'mold'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'damp') THEN 'damp'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dusty') THEN 'dusty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'petrichor') THEN 'petrichor'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'amber') THEN 'amber'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'earth') THEN 'earthy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'must') THEN 'musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'musk') THEN 'musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cannabis') THEN 'cannabis'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mushroom') THEN 'mushroom'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'phenolic') THEN 'phenolic'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'animalic') THEN 'animalic'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'meat') THEN 'meaty/brothy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'broth') THEN 'meaty/brothy'

             ELSE 'other' END AS taste

    FROM split_temp

),

detailed_category as (

    select
        coffee_id,
        tasting_notes,
        CASE

             WHEN taste = 'blackberry' THEN 'blackberry'
             WHEN taste = 'raspberry' THEN 'raspberry'
             WHEN taste = 'blueberry' THEN 'blueberry'
             WHEN taste = 'strawberry' THEN 'strawberry'
             WHEN taste = 'currant' THEN 'berry'
             WHEN taste = 'other berry' THEN 'berry'
             WHEN taste = 'mulberry' THEN 'berry'
             WHEN taste = 'boysenberry' THEN 'berry'
             WHEN taste = 'elderberry' THEN 'berry'
             WHEN taste = 'gooseberry' THEN 'berry'
             WHEN taste = 'cranberry' THEN 'berry'
             WHEN taste = 'goji berry' THEN 'berry'

             WHEN taste = 'raisin' THEN 'raisin'
             WHEN taste = 'golden_raisin' THEN 'raisin'
             WHEN taste = 'prune' THEN 'prune'
             WHEN taste =  'dried plum' THEN 'prune'
             WHEN taste =  'date' THEN 'dried fruit'

             WHEN taste = 'coconut' THEN 'coconut'
             WHEN taste = 'cherry' THEN 'cherry'
             WHEN taste = 'pomegranate' THEN 'pomegranate'
             WHEN taste = 'pinapple' THEN 'pinapple'
             WHEN taste = 'grape' THEN 'grape'
             WHEN taste = 'apple' THEN 'apple'
             WHEN taste = 'peach' THEN 'peach'
             WHEN taste = 'pear' THEN 'pear'
             WHEN taste = 'banana' THEN 'other fruit'
             WHEN taste = 'juicy' THEN 'other fruit'
             WHEN taste = 'juniper' THEN 'other fruit'
             WHEN taste = 'persimmon' THEN 'other fruit'
             WHEN taste = 'apricot' THEN 'other fruit'
             WHEN taste = 'plum' THEN 'other fruit'
             WHEN taste = 'fig' THEN 'other fruit'
             WHEN taste = 'pluot' THEN 'other fruit'
             WHEN taste = 'tamarind' THEN 'other fruit'
             WHEN taste = 'rhubarb' THEN 'other fruit'
             WHEN taste = 'tomato' THEN 'other fruit'
             WHEN taste = 'guava' THEN 'other fruit'
             WHEN taste = 'papaya' THEN 'other fruit'
             WHEN taste = 'lychee' THEN 'other fruit'
             WHEN taste = 'passion' THEN 'other fruit'
             WHEN taste = 'starfruit' THEN 'other fruit'
             WHEN taste = 'mango' THEN 'other fruit'
             WHEN taste = 'melon' THEN 'other fruit'
             WHEN taste = 'cantaloupe' THEN 'other fruit'
             WHEN taste = 'honeydew' THEN 'other fruit'
             WHEN taste = 'breadfruit' THEN 'other fruit'
             WHEN taste = 'loquat' THEN 'other fruit'

             WHEN taste = 'grapefruit' THEN 'grapefruit'
             WHEN taste = 'orange' THEN 'orange'
             WHEN taste = 'lemon' THEN 'lemon'
             WHEN taste = 'lime' THEN 'lime'
             WHEN taste = 'bergamot' THEN 'citrus fruit'
             WHEN taste = 'tangerine' THEN 'citrus fruit'
             WHEN taste = 'nectarine' THEN 'citrus fruit'
             WHEN taste = 'mandarin' THEN 'citrus fruit'
             WHEN taste = 'kumquat' THEN 'citrus fruit'
             WHEN taste = 'pomelo' THEN 'citrus fruit'
             WHEN taste = 'yuzu' THEN 'citrus fruit'
             WHEN taste = 'sumac' THEN 'citrus fruit'
             WHEN taste = 'citrus' THEN 'citrus fruit'
             WHEN taste = 'clementine' THEN 'citrus fruit'
             WHEN taste = 'quince' THEN 'citrus fruit'

             WHEN taste = 'fruit' THEN 'other fruit'

             WHEN taste = 'wine' THEN 'wine'
             WHEN taste = 'whiskey' THEN 'whiskey'
             WHEN taste = 'ferment' THEN 'fermented'
             WHEN taste = 'overripe' THEN 'overripe'
             WHEN taste = 'rum' THEN 'alcohol/fermented'
             WHEN taste = 'grappa' THEN 'alcohol/fermented'
             WHEN taste = 'brandy' THEN 'alcohol/fermented'
             WHEN taste = 'cognac' THEN 'alcohol/fermented'
             WHEN taste = 'bourbon' THEN 'alcohol/fermented'
             WHEN taste = 'tequila' THEN 'alcohol/fermented'
             WHEN taste = 'fraamboise' THEN 'alcohol/fermented'
             WHEN taste = 'contreau' THEN 'alcohol/fermented'
             WHEN taste = 'liqueur' THEN 'alcohol/fermented'
             WHEN taste = 'alcohol' THEN 'alcohol/fermented'
             WHEN taste = 'yogurt' THEN 'alcohol/fermented'
             WHEN taste = 'milk' THEN 'alcohol/fermented'
             WHEN taste = 'cheese' THEN 'alcohol/fermented'

             WHEN taste = 'olive oil' THEN 'olive oil'
             WHEN taste = 'raw' THEN 'raw'
             WHEN taste = 'under-ripe' THEN 'under-ripe'
             WHEN taste = 'peapod' THEN 'peapod'
             WHEN taste = 'fresh' THEN 'fresh'
             WHEN taste = 'dark green' THEN 'dark green'
             WHEN taste = 'vegetable' THEN 'vegetative'
             WHEN taste = 'vegetative' THEN 'vegetative'
             WHEN taste = 'hay' THEN 'hay-like'
             WHEN taste = 'bean' THEN 'beany'
             WHEN taste = 'mint' THEN 'fresh'
             WHEN taste = 'parsely' THEN 'hay-like'
             WHEN taste = 'grass' THEN 'fresh'
             WHEN taste = 'hop' THEN 'fresh'
             WHEN taste = 'bay leaf' THEN 'herb-like'
             WHEN taste = 'thyme' THEN 'herb-like'
             WHEN taste = 'ginseng' THEN 'green/vegetative'
             WHEN taste = 'ginger' THEN 'green/vegetative'
             WHEN taste = 'marjoram' THEN 'green/vegetative'
             WHEN taste = 'tarragon' THEN 'green/vegetative'
             WHEN taste = 'sarsaparilla' THEN 'green/vegetative'
             WHEN taste = 'frankincense' THEN 'green/vegetative'
             WHEN taste = 'oregano' THEN 'green/vegetative'
             WHEN taste = 'fennel' THEN 'green/vegetative'
             WHEN taste = 'cilantro' THEN 'green/vegetative'
             WHEN taste = 'dill' THEN 'green/vegetative'
             WHEN taste = 'turmeric' THEN 'green/vegetative'
             WHEN taste = 'herb' THEN 'herb-like'

             WHEN taste = 'malt' THEN 'malt'
             WHEN taste = 'cereal' THEN 'cereal'
             WHEN taste = 'grain' THEN 'grain'
             WHEN taste = 'rice' THEN 'cereal'
             
             WHEN taste = 'pungent' THEN 'pungent'
             WHEN taste = 'pepper' THEN 'pepper'
             WHEN taste = 'anise' THEN 'anise'
             WHEN taste = 'nutmeg' THEN 'nutmeg'
             WHEN taste = 'mace' THEN 'nutmeg'
             WHEN taste = 'cinammon' THEN 'cinammon'
             WHEN taste = 'clove' THEN 'clove'
             WHEN taste = 'cardamom' THEN 'brown spice'
             WHEN taste = 'myrrh' THEN 'brown spice'
             WHEN taste = 'coriander' THEN 'brown spice'
             WHEN taste = 'cumin' THEN 'brown spice'
             WHEN taste = 'mustard' THEN 'brown spice'
             WHEN taste = 'cayenne' THEN 'brown spice'
             WHEN taste = 'cellery seed' THEN 'brown spice'
             WHEN taste = 'paprika' THEN 'brown spice'
             WHEN taste = 'saffron' THEN 'brown spice'
             WHEN taste = 'spicy' THEN 'spices'
             WHEN taste = 'spice' THEN 'spices'

             WHEN taste = 'peanuts' THEN 'peanuts'
             WHEN taste = 'hazelnut' THEN 'hazelnut'
             WHEN taste = 'almond' THEN 'almond'
             WHEN taste = 'pistachio' THEN 'nutty'
             WHEN taste = 'cashew' THEN 'nutty'
             WHEN taste = 'pecan' THEN 'nutty'
             WHEN taste = 'frangipane' THEN 'almond'
             WHEN taste = 'marzipan' THEN 'almond'
             WHEN taste = 'macadamia' THEN 'nutty'
             WHEN taste = 'hempseed' THEN 'nutty'
             WHEN taste = 'taro' THEN 'nutty'
             WHEN taste = 'nut' THEN 'nutty'

             WHEN taste = 'dark chocolate' THEN 'dark chocolate'
             WHEN taste = 'chocolate' THEN 'chocolate'
             WHEN taste = 'cocoa' THEN 'dark chocolate'
             
             WHEN taste = 'molasses' THEN 'molasses'
             WHEN taste = 'toffee' THEN 'caramelized'
             WHEN taste = 'maple syrup' THEN 'maple syrup'
             WHEN taste = 'caramel' THEN 'caramelized'
             WHEN taste = 'butterscotch' THEN 'caramelized'
             WHEN taste = 'brown sugar' THEN 'brown sugar'
             WHEN taste = 'creme brulee' THEN 'caramelized'
             WHEN taste = 'honey' THEN 'honey'
             
             WHEN taste = 'vanilla' THEN 'vanilla'
             WHEN taste = 'vanillin' THEN 'vanillin'
             WHEN taste = 'sweet aromatics' THEN 'sweet aromatics'
             WHEN taste = 'jolly rancher' THEN 'overall sweet'
             WHEN taste = 'bubblegum' THEN 'overall sweet'
             WHEN taste = 'cream' THEN 'overall sweet'
             WHEN taste = 'nougat' THEN 'overall sweet'
             WHEN taste = 'halvah' THEN 'overall sweet'
             WHEN taste = 'praline' THEN 'overall sweet'
             WHEN taste = 'agave' THEN 'overall sweet'
             WHEN taste = 'candy' THEN 'overall sweet'
             WHEN taste = 'taffy' THEN 'overall sweet'
             WHEN taste = 'marshmallow' THEN 'overall sweet'
             WHEN taste = 'sugar' THEN 'overall sweet'
             WHEN taste = 'sweet' THEN 'overall sweet'

             WHEN taste = 'sour' THEN 'sour'
             
             WHEN taste = 'black tea' THEN 'black tea'

             WHEN taste = 'chamomile' THEN 'chamomile'
             WHEN taste = 'rose' THEN 'rose'
             WHEN taste = 'jasmine' THEN 'jasmine'
             WHEN taste = 'gardenia' THEN 'floral'
             WHEN taste = 'freesia' THEN 'floral'
             WHEN taste = 'magnolia' THEN 'floral'
             WHEN taste = 'honeysuckle' THEN 'floral'
             WHEN taste = 'wisteria' THEN 'floral'
             WHEN taste = 'verbena' THEN 'floral'
             WHEN taste = 'lily' THEN 'floral'
             WHEN taste = 'nasturtium' THEN 'floral'
             WHEN taste = 'lilac' THEN 'floral'
             WHEN taste = 'carnation' THEN 'floral'
             WHEN taste = 'narcissus' THEN 'floral'
             WHEN taste = 'blossom' THEN 'floral'
             WHEN taste = 'violet' THEN 'floral'
             WHEN taste = 'rhododendron' THEN 'floral'
             WHEN taste = 'hibiscus' THEN 'floral'
             WHEN taste = 'tea' THEN 'floral'
             WHEN taste = 'wisteria' THEN 'floral'
             WHEN taste = 'orchid' THEN 'floral'
             WHEN taste = 'lantana' THEN 'floral'
             WHEN taste = 'alyssum' THEN 'floral'
             WHEN taste = 'lavender' THEN 'floral'
             WHEN taste = 'perfumed' THEN 'floral'
             WHEN taste = 'hyacinth' THEN 'floral'
             WHEN taste = 'azalea' THEN 'floral'
             WHEN taste = 'osmanthus' THEN 'floral'
             WHEN taste = 'chrysanthemum' THEN 'floral'
             WHEN taste = 'floral' THEN 'floral'
             WHEN taste = 'flower' THEN 'floral'

             WHEN taste = 'bitter' THEN 'bitter'
             WHEN taste = 'salty' THEN 'salty'
             WHEN taste = 'medicinal' THEN 'medicinal'
             WHEN taste = 'petroleum' THEN 'petroleum'
             WHEN taste = 'skunky' THEN 'skunky'
             WHEN taste = 'rubber' THEN 'rubber'

             WHEN taste = 'pipe tobacco' THEN 'pipe tobacco'
             WHEN taste = 'tobacco' THEN 'tobacco'
             WHEN taste = 'acrid' THEN 'acrid'
             WHEN taste = 'ashy' THEN 'ashy'
             WHEN taste = 'smoky' THEN 'smoky'
             WHEN taste = 'roasted' THEN 'roasted'
             WHEN taste = 'leather' THEN 'burnt'
             WHEN taste = 'teriyaki sauce' THEN 'burnt'
             WHEN taste = 'tamari' THEN 'burnt'
             WHEN taste = 'bold' THEN 'burnt'

             WHEN taste = 'stale' THEN 'stale'
             WHEN taste = 'cardboard' THEN 'cardboard'
             WHEN taste = 'paper' THEN 'papery'
             WHEN taste = 'cedar' THEN 'woody'
             WHEN taste = 'wood' THEN 'woody'
             WHEN taste = 'oak' THEN 'woody'
             WHEN taste = 'fir' THEN 'woody'
             WHEN taste = 'mesquite' THEN 'woody'
             WHEN taste = 'elm' THEN 'woody'
             WHEN taste = 'sassafras' THEN 'woody'
             WHEN taste = 'balsa' THEN 'woody'
             WHEN taste = 'barley' THEN 'woody'
             WHEN taste = 'bay tree' THEN 'woody'
             WHEN taste = 'pine' THEN 'woody'
             WHEN taste = 'eucalyptus' THEN 'woody'
             WHEN taste = 'palo santo' THEN 'woody'
             WHEN taste = 'moist' THEN 'moldy/damp'
             WHEN taste = 'mold' THEN 'moldy/damp'
             WHEN taste = 'damp' THEN 'moldy/damp'
             WHEN taste = 'dusty' THEN 'musty/dusty'
             WHEN taste = 'petrichor' THEN 'musty/earthy'
             WHEN taste = 'amber' THEN 'musty/earthy'
             WHEN taste = 'earth' THEN 'musty/earthy'
             WHEN taste = 'must' THEN 'musty/earthy'
             WHEN taste = 'musk' THEN 'musty/earthy'
             WHEN taste = 'cannabis' THEN 'musty/earthy'
             WHEN taste = 'mushroom' THEN 'musty/earthy'
             WHEN taste = 'phenolic' THEN 'phenolic'
             WHEN taste = 'animalic' THEN 'animalic'
             WHEN taste = 'meat/brothy' THEN 'meaty/brothy'

            ELSE 'other' END AS detailed_category

    FROM taste
),

descriptive_category as (

    select
        coffee_id,
        tasting_notes,
        CASE
             WHEN detailed_category = 'blackberry' THEN 'berry'
             WHEN detailed_category = 'raspberry' THEN 'berry'
             WHEN detailed_category = 'blueberry' THEN 'berry'
             WHEN detailed_category = 'strawberry' THEN 'berry'
             WHEN detailed_category = 'berry' THEN 'berry'

             WHEN detailed_category = 'raisin' THEN 'dried fruit'
             WHEN detailed_category = 'prune' THEN 'dried fruit'
             WHEN detailed_category = 'dried fruit' THEN 'dried fruit'

             WHEN detailed_category = 'coconut' THEN 'other fruit'
             WHEN detailed_category = 'cherry' THEN 'other fruit'
             WHEN detailed_category = 'pomegranate' THEN 'other fruit'
             WHEN detailed_category = 'pinapple' THEN 'other fruit'
             WHEN detailed_category = 'grape' THEN 'other fruit'
             WHEN detailed_category = 'apple' THEN 'other fruit'
             WHEN detailed_category = 'stone_fruit' THEN 'other fruit'
             WHEN detailed_category = 'pear' THEN 'other fruit'
             WHEN detailed_category = 'other fruit' THEN 'other fruit'

             WHEN detailed_category = 'grapefruit' THEN 'citrus fruit'
             WHEN detailed_category = 'orange' THEN 'citrus fruit'
             WHEN detailed_category = 'lemon' THEN 'citrus fruit'
             WHEN detailed_category = 'lime' THEN 'citrus fruit'
             WHEN detailed_category = 'citrus fruit' THEN 'citrus fruit'

             WHEN detailed_category = 'wine' THEN 'alcohol/fermented'
             WHEN detailed_category = 'whiskey' THEN 'alcohol/fermented'
             WHEN detailed_category = 'ferment' THEN 'alcohol/fermented'
             WHEN detailed_category = 'overripe' THEN 'alcohol/fermented'
             WHEN detailed_category = 'alcohol/fermented' THEN 'alcohol/fermented'

             WHEN detailed_category = 'olive oil' THEN 'olive oil'

             WHEN detailed_category = 'raw' THEN 'raw'

             WHEN detailed_category = 'under-ripe' THEN 'green/vegetative'
             WHEN detailed_category = 'peapod' THEN 'green/vegetative'
             WHEN detailed_category = 'fresh' THEN 'green/vegetative'
             WHEN detailed_category = 'dark green' THEN 'green/vegetative'
             WHEN detailed_category = 'vegetative' THEN 'green/vegetative'
             WHEN detailed_category = 'hay' THEN 'green/vegetative'
             WHEN detailed_category = 'herb-like' THEN 'green/vegetative'
             WHEN detailed_category = 'green/vegetative' THEN 'green/vegetative'

             WHEN detailed_category = 'beany' THEN 'beany'

             WHEN detailed_category = 'malt' THEN 'cereal'
             WHEN detailed_category = 'cereal' THEN 'cereal'
             WHEN detailed_category = 'grain' THEN 'cereal'

             WHEN detailed_category = 'pungent' THEN 'pungent'
             WHEN detailed_category = 'pepper' THEN 'pepper'
             WHEN detailed_category = 'anise' THEN 'brown spice'
             WHEN detailed_category = 'nutmeg' THEN 'brown spice'
             WHEN detailed_category = 'cinammon' THEN 'brown spice'
             WHEN detailed_category = 'clove' THEN 'brown spice'
             WHEN detailed_category = 'brown spice' THEN 'brown spice'
             WHEN detailed_category = 'spicy' THEN 'brown spice'
             WHEN detailed_category = 'spice' THEN 'brown spice'

             WHEN detailed_category = 'peanuts' THEN 'nutty'
             WHEN detailed_category = 'hazelnut' THEN 'nutty'
             WHEN detailed_category = 'almond' THEN 'nutty'
             WHEN detailed_category = 'nutty'THEN 'nutty'

             WHEN detailed_category = 'dark chocolate' THEN 'cocoa'
             WHEN detailed_category = 'chocolate' THEN 'cocoa'
             WHEN detailed_category = 'cocoa' THEN 'cocoa'
             
             WHEN detailed_category = 'molasses' THEN 'brown sugar'
             WHEN detailed_category = 'maple syrup' THEN 'brown sugar'
             WHEN detailed_category = 'caramelized' THEN 'brown sugar'
             WHEN detailed_category = 'brown sugar' THEN 'brown sugar'
             WHEN detailed_category = 'honey' THEN 'brown sugar'

             WHEN detailed_category = 'vanilla' THEN 'vanilla'
             WHEN detailed_category = 'vanillin' THEN 'vanillin'
             WHEN detailed_category = 'sweet aromatics' THEN 'sweet aromatics'
             WHEN detailed_category = 'jolly rancher' THEN 'overall sweet'

             WHEN detailed_category = 'sour' THEN 'sour'
             
             WHEN detailed_category = 'black tea' THEN 'black tea'

             WHEN detailed_category = 'chamomile' THEN 'floral'
             WHEN detailed_category = 'rose' THEN 'floral'
             WHEN detailed_category = 'jasmine' THEN 'floral'
             WHEN detailed_category = 'floral' THEN 'floral'

             WHEN detailed_category = 'bitter' THEN 'chemical'
             WHEN detailed_category = 'salty' THEN 'chemical'
             WHEN detailed_category = 'medicinal' THEN 'chemical'
             WHEN detailed_category = 'petroleum' THEN 'chemical'
             WHEN detailed_category = 'skunky' THEN 'chemical'
             WHEN detailed_category = 'rubber' THEN 'chemical'

             WHEN detailed_category = 'pipe tobacco' THEN 'pipe tobacco'
             WHEN detailed_category = 'tobacco' THEN 'tobacco'

             WHEN detailed_category = 'acrid' THEN 'burnt'
             WHEN detailed_category = 'ashy' THEN 'burnt'
             WHEN detailed_category = 'smoky' THEN 'burnt'
             WHEN detailed_category = 'roasted' THEN 'burnt'
             WHEN detailed_category = 'burnt' THEN 'burnt'

             WHEN detailed_category = 'stale' THEN 'papery/musty'
             WHEN detailed_category = 'cardboard' THEN 'papery/musty'
             WHEN detailed_category = 'paper' THEN 'papery/musty'
             WHEN detailed_category = 'cedar' THEN 'papery/musty'
             WHEN detailed_category = 'damp' THEN 'papery/musty'
             WHEN detailed_category = 'dusty' THEN 'papery/musty'
             WHEN detailed_category = 'petrichor' THEN 'papery/musty'
             WHEN detailed_category = 'phenolic' THEN 'papery/musty'
             WHEN detailed_category = 'animalic' THEN 'papery/musty'
             WHEN detailed_category = 'meat/brothy' THEN 'papery/musty'
            
             ELSE 'other' END AS descriptive_category

    FROM detailed_category

),

general_category as (

    select
        coffee_id,
        tasting_notes,
        CASE
             WHEN descriptive_category = 'berry' THEN 'fruity'
             WHEN descriptive_category = 'dried fruit' THEN 'fruity'
             WHEN descriptive_category = 'other fruit' THEN 'fruity'
             WHEN descriptive_category = 'citrus fruit' THEN 'fruity'

             WHEN descriptive_category = 'sour' THEN 'sour/fermented'
             WHEN descriptive_category = 'alcohol/fermented' THEN 'sour/fermented'
             
             WHEN descriptive_category = 'olive oil' THEN 'green/vegetative'
             WHEN descriptive_category = 'raw' THEN 'green/vegetative'
             WHEN descriptive_category = 'green/vegetative' THEN 'green/vegetative'
             WHEN descriptive_category = 'beany' THEN 'green/vegetative'

             WHEN descriptive_category = 'papery/musty' THEN 'other'
             WHEN descriptive_category = 'chemical' THEN 'other'

             WHEN descriptive_category = 'pipe tobacco' THEN 'roasted'
             WHEN descriptive_category = 'tobacco' THEN 'roasted'
             WHEN descriptive_category = 'burnt' THEN 'roasted'
             WHEN descriptive_category = 'cereal' THEN 'roasted'

             WHEN descriptive_category = 'pungent' THEN 'spices'
             WHEN descriptive_category = 'pepper' THEN 'spices'
             WHEN descriptive_category = 'brown spice' THEN 'spices'

             WHEN descriptive_category = 'nutty' THEN 'nutty/cocoa'
             WHEN descriptive_category = 'cocoa' THEN 'nutty/cocoa'

             WHEN descriptive_category = 'brown sugar' THEN 'sweet'
             WHEN descriptive_category = 'vanilla' THEN 'sweet'
             WHEN descriptive_category = 'vanillin' THEN 'sweet'
             WHEN descriptive_category = 'overall sweet' THEN 'sweet'
             WHEN descriptive_category = 'sweet aromatics' THEN 'sweet'

             WHEN descriptive_category = 'black tea' THEN 'floral'
             WHEN descriptive_category = 'floral' THEN 'floral'

             ELSE 'other' END AS general_category

    FROM descriptive_category

)

select
    taste.coffee_id,
    REPLACE((
    REPLACE((
    REPLACE((
    REPLACE((
    REPLACE(
    LTRIM(taste.tasting_notes), ' in aroma and cup', ''))
    , 'a hint of ', ''))
    , 'fresh-cut ', ''))
    , 'hint of ', ''))
    , '-like flowers', '')
    as tasting_notes,
    taste.taste,
    detailed_category.detailed_category,
    descriptive_category.descriptive_category,
    general_category.general_category
from taste
join detailed_category using coffee_id
join descriptive_category using coffee_id
join general_category using coffee_id