with reviews as (

    select * from {{ ref('dim_review') }}

),

split_temp as (

    select 
        coffee_id,
        tasting_notes
    from reviews,
         UNNEST(SPLIT(LOWER(tasting_notes))) as tasting_notes
         with OFFSET AS offset
         order by offset

),

categories as (

    select
        coffee_id,
        tasting_notes,
        CASE
             WHEN CONTAINS_SUBSTR(tasting_notes , 'blackberry') THEN 'blackberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mulberry') THEN 'mulberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'boysenberry') THEN 'boysenberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'elderberry') THEN 'elderberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'raspberry') THEN 'raspberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'blueberry') THEN 'blueberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'gooseberry') THEN 'gooseberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'strawberry') THEN 'strawberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cranberry') THEN 'cranberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'goji') THEN 'goji berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'currant') THEN 'currant'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'berry') THEN 'other berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'berries') THEN 'other berry'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'raisin') THEN 'raisin'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'golden raisin') THEN 'golden_raisin'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'prune') THEN 'prune'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dried plum') THEN 'prune'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'date') THEN 'date'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'coconut') THEN 'coconut'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cherry') THEN 'cherry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pomegranate') THEN 'pomegranate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pinapple') THEN 'pinapple'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grape') THEN 'grape'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'apple') THEN 'apple'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'peach') THEN 'peach'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pear') THEN 'pear'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'banana') THEN 'banana'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'juicy') THEN 'juicy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'juniper') THEN 'juniper'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'persimmon') THEN 'persimmon'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'apricot') THEN 'apricot'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'plum') THEN 'plum'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fig') THEN 'fig'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pluot') THEN 'pluot'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tamarind') THEN 'tamarind'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rhubarb') THEN 'rhubarb'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tomato') THEN 'tomato'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'guava') THEN 'guava'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'papaya') THEN 'papaya'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lychee') THEN 'lychee'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'passion') THEN 'passion fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'starfruit') THEN 'star fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mango') THEN 'mango'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'melon') THEN 'melon'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cantaloupe') THEN 'cantaloupe'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'honeydew') THEN 'honeydew'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'breadfruit') THEN 'breadfruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'loquat') THEN 'loquat'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruit-toned') THEN 'fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruit-forward') THEN 'fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruity') THEN 'fruit'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'lemon') THEN 'lemon'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grapefruit') THEN 'grapefruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pomelo') THEN 'pomelo'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'orange') THEN 'orange'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bergamot') THEN 'bergamot'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tangerine') THEN 'tangerine'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nectarine') THEN 'nectarine'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mandarin') THEN 'mandarin'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'kumquat') THEN 'kumquat'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lime') THEN 'lime'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'yuzu') THEN 'yuzu'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sumac') THEN 'sumac'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'citrus') THEN 'citrus'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'clementine') THEN 'clementine'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'quince') THEN 'quince'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruit') THEN 'fruit'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'rum') THEN 'rum'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grappa') THEN 'grappa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'brandy') THEN 'brandy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cognac') THEN 'cognac'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'whiskey') THEN 'whiskey'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wine') THEN 'wine'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'yogurt') THEN 'yogurt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'milk') THEN 'milk'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cheese') THEN 'cheese'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pinot noir') THEN 'wine'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bourbon') THEN 'bourbon'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tequila') THEN 'tequila'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'framboise') THEN 'framboise'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cointreau') THEN 'cointreau'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'liqueur') THEN 'liqueur'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ferment') THEN 'ferment'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'overripe') THEN 'overripe'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'alcohol') THEN 'alcohol'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'oliv e oil') THEN 'olive oil'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'raw') THEN 'raw'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'under-ripe') THEN 'under-ripe'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'peapod') THEN 'peapod'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fresh') THEN 'fresh'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dark green') THEN 'dark green'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vegetable') THEN 'vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vegetative') THEN 'vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hay') THEN 'hay-like'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'herb') THEN 'herb-like'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bean') THEN 'beany'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mint') THEN 'mint'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'parsely') THEN 'parsely'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'parsley') THEN 'parsely'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grass') THEN 'grass'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hop') THEN 'hop'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bay leaf') THEN 'bay leaf'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'thyme') THEN 'thyme'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ginseng') THEN 'ginseng'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ginger') THEN 'ginger'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'marjoram') THEN 'marjoram'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tarragon') THEN 'tarragon'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sarsaparilla') THEN 'sarsaparilla'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'frankincense') THEN 'frankincense'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'frankinense') THEN 'frankincense'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'oregano') THEN 'oregano'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fennel') THEN 'fennel'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cilantro') THEN 'cilantro'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dill') THEN 'dill'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'herb') THEN 'herb-like'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'turmeric') THEN 'turmeric'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'malt') THEN 'malt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cereal') THEN 'cereal'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grain') THEN 'grain'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'graham cracker') THEN 'grain'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rice') THEN 'rice'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sage') THEN 'pungent'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pungent') THEN 'pungent'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pepper') THEN 'pepper'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'anise') THEN 'anise'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nutmeg') THEN 'nutmeg'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mace') THEN 'mace'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cinammon') THEN 'cinammon'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cinnamon') THEN 'cinammon'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'clove') THEN 'clove'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cardamom') THEN 'cardamom'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'myrrh') THEN 'myrrh'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'myrhh') THEN 'myrrh'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'coriander') THEN 'coriander'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cumin') THEN 'cumin'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mustard') THEN 'mustard'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cayenne') THEN 'cayenne'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'celery seed') THEN 'celery seed'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'paprika') THEN 'paprika'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'saffron') THEN 'saffron'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'spicy') THEN 'spicy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'spice') THEN 'spice'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'peanuts') THEN 'peanuts'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hazelnut') THEN 'hazelnut'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'almond') THEN 'almond'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pistachio') THEN 'pistachio'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cashew') THEN 'cashew'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pecan') THEN 'pecan'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'frangipane') THEN 'frangipane'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'marzipan') THEN 'marzipan'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'macadamia') THEN 'macadamia'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hemp-seed') THEN 'hemp-seed'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'taro') THEN 'taro'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nut') THEN 'nutty'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'dark chocolate') THEN 'dark chocolate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chocolate') THEN 'chocolate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chocolaty') THEN 'chocolate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cocoa') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cacao') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cocoo') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cocao') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'carob') THEN 'carob'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tiramisu') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fudge') THEN 'chocolate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'oreo') THEN 'chocolate'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'molasses') THEN 'molasses'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'toffee') THEN 'caramel'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'maple syrup') THEN 'maple syrup'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'caramel') THEN 'caramelized'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'butterscotch') THEN 'butterscotch'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'brown sugar') THEN 'brown sugar'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'creme brulee') THEN 'creme brulee'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'agave') THEN 'agave'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'honey') THEN 'honey'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vanilla') THEN 'vanilla'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vanillin') THEN 'vanillin'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sweet aromatics') THEN 'sweet aromatics'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'jolly rancher') THEN 'jolly rancher'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bubblegum') THEN 'bubble gum'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cream') THEN 'cream'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nougat') THEN 'nougat'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'halvah') THEN 'halvah'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'praline') THEN 'praline'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'candy') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'taffy') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'marshmallow') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sugar') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sweet') THEN 'overall sweet'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'sour') THEN 'sour'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'acid') THEN 'sour'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bright') THEN 'sour'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'crisp') THEN 'sour'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tart') THEN 'sour'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'black tea') THEN 'black tea'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chamomile') THEN 'chamomile'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rose') THEN 'rose'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'jasmine') THEN 'jasmine'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'gardenia') THEN 'gardenia'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'freesia') THEN 'freesia'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'magnolia') THEN 'magnolia'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'honeysuckle') THEN 'honeysuckle'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wisteria') THEN 'wisteria'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'verbena') THEN 'verbena'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lily') THEN 'lily'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nasturtium') THEN 'nasturtium'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lilac') THEN 'lilac'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'carnation') THEN 'carnation'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'narcissus') THEN 'narcissus'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'blossom') THEN 'blossom'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'violet') THEN 'violet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rhododendron') THEN 'rhododendron'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hibiscus') THEN 'hibiscus'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tea') THEN 'tea'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wisteria') THEN 'wisteria'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'orchid') THEN 'orchid'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lantana') THEN 'lantana'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'alyssum') THEN 'alyssum'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lavender') THEN 'lavender'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'perfumed') THEN 'perfumed'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hyacinth') THEN 'hyacinth'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'azalea') THEN 'azalea'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'osmanthus') THEN 'osmanthus'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chrysanthemum') THEN 'chrysanthemum'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'floral') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'flower') THEN 'floral'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'bitter') THEN 'bitter'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'salty') THEN 'salty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'medicinal') THEN 'medicinal'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'petroleum') THEN 'petroleum'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'skunky') THEN 'skunky'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rubber') THEN 'rubber'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'pipe tobacco') THEN 'pipe tobacco'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tobacco') THEN 'tobacco'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'acrid') THEN 'acrid'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'burnt') THEN 'ashy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ash') THEN 'ashy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'scorched') THEN 'ashy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'smoky') THEN 'smoky'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'toasted') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'roast-toned') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'roast-prominent') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'leather') THEN 'leather'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'teriyaki sauce') THEN 'teriyaki sauce'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tamari') THEN 'tamari'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bold') THEN 'bold'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'stale') THEN 'stale'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cardboard') THEN 'cardboard'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'paper') THEN 'papery'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cedar') THEN 'cedar'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wood') THEN 'wood'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'oak') THEN 'oak'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fir') THEN 'fir'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mesquite') THEN 'mesquite'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'elm') THEN 'elm'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sassafras') THEN 'sassafras'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'balsa') THEN 'balsa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'barley') THEN 'barley'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bay tree') THEN 'bay'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pine') THEN 'pine'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'eucalyptus') THEN 'eucalyptus'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'palo santo') THEN 'palo santo'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'moist') THEN 'moist'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mold') THEN 'mold'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'damp') THEN 'damp'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dusty') THEN 'dusty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'petrichor') THEN 'petrichor'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'amber') THEN 'amber'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'earth') THEN 'earthy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'must') THEN 'musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'musk') THEN 'musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cannabis') THEN 'cannabis'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mushroom') THEN 'mushroom'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'phenolic') THEN 'phenolic'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'animalic') THEN 'animalic'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'meat') THEN 'meaty/brothy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'broth') THEN 'meaty/brothy'

             ELSE 'other' END AS taste,
             
        CASE
             WHEN CONTAINS_SUBSTR(tasting_notes , 'blackberry') THEN 'blackberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mulberry') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'boysenberry') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'elderberry') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'raspberry') THEN 'raspberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'blueberry') THEN 'blueberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'gooseberry') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'strawberry') THEN 'strawberry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cranberry') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'goji') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'currant') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'berry') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'berries') THEN 'berry'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'raisin') THEN 'raisin'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'golden raisin') THEN 'raisin'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'prune') THEN 'prune'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dried plum') THEN 'prune'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'date') THEN 'dried fruit'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'coconut') THEN 'coconut'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cherry') THEN 'cherry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pomegranate') THEN 'pomegranate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pinapple') THEN 'pinapple'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grape') THEN 'grape'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'apple') THEN 'apple'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'peach') THEN 'peach'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pear') THEN 'pear'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'banana') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'juicy') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'juniper') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'persimmon') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'apricot') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'plum') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fig') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pluot') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tamarind') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rhubarb') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tomato') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'guava') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'papaya') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lychee') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'passion') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'starfruit') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mango') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'melon') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cantaloupe') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'honeydew') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'breadfruit') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'loquat') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruit-toned') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruit-forward') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruity') THEN 'other fruit'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'lemon') THEN 'lemon'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grapefruit') THEN 'grapefruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pomelo') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'orange') THEN 'orange'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bergamot') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tangerine') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nectarine') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mandarin') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'kumquat') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lime') THEN 'lime'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'yuzu') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sumac') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'citrus') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'clementine') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'quince') THEN 'citrus fruit'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruit') THEN 'other fruit'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'rum') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grappa') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'brandy') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cognac') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'whiskey') THEN 'whiskey'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wine') THEN 'wine'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'yogurt') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'milk') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cheese') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pinot noir') THEN 'wine'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bourbon') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tequila') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'framboise') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cointreau') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'liqueur') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ferment') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'overripe') THEN 'overripe'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'alcohol') THEN 'alcohol/fermented'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'olive oil') THEN 'olive oil'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'raw') THEN 'raw'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'under-ripe') THEN 'under-ripe'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'peapod') THEN 'peapod'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fresh') THEN 'fresh'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dark green') THEN 'dark green'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vegetable') THEN 'vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vegetative') THEN 'vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hay') THEN 'hay-like'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'herb') THEN 'herb-like'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bean') THEN 'beany'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mint') THEN 'fresh'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'parsely') THEN 'hay-like'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'parsley') THEN 'hay-like'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grass') THEN 'fresh'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hop') THEN 'fresh'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bay leaf') THEN 'herb-like'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'thyme') THEN 'herb-like'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ginseng') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ginger') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'marjoram') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tarragon') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sarsaparilla') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'frankincense') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'frankinense') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'oregano') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fennel') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cilantro') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dill') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'herb') THEN 'herb-like'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'turmeric') THEN 'green/vegetative'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'malt') THEN 'malt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cereal') THEN 'cereal'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grain') THEN 'grain'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'graham cracker') THEN 'grain'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rice') THEN 'cereal'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sage') THEN 'pungent'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pungent') THEN 'pungent'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pepper') THEN 'pepper'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'anise') THEN 'anise'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nutmeg') THEN 'nutmeg'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mace') THEN 'mace'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cinammon') THEN 'cinammon'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cinnamon') THEN 'cinammon'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'clove') THEN 'clove'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cardamom') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'myrrh') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'myrhh') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'coriander') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cumin') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mustard') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cayenne') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'celery seed') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'paprika') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'saffron') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'spicy') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'spice') THEN 'spices'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'peanuts') THEN 'peanuts'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hazelnut') THEN 'hazelnut'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'almond') THEN 'almond'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pistachio') THEN 'nutty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cashew') THEN 'nutty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pecan') THEN 'nutty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'frangipane') THEN 'almond'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'marzipan') THEN 'almond'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'macadamia') THEN 'nutty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hemp-seed') THEN 'nutty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'taro') THEN 'nutty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nut') THEN 'nutty'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'dark chocolate') THEN 'dark chocolate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chocolate') THEN 'chocolate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chocolaty') THEN 'chocolate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cocoa') THEN 'dark chocolate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cacao') THEN 'dark chocolate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cocoo') THEN 'dark chocolate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cocao') THEN 'dark chocolate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'carob') THEN 'chocolate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tiramisu') THEN 'dark chocolate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fudge') THEN 'chocolate'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'oreo') THEN 'chocolate'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'molasses') THEN 'molasses'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'toffee') THEN 'caramelized'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'maple syrup') THEN 'maple syrup'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'caramel') THEN 'caramelized'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'butterscotch') THEN 'caramelized'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'brown sugar') THEN 'brown sugar'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'creme brulee') THEN 'caramelized'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'honey') THEN 'honey'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vanilla') THEN 'vanilla'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vanillin') THEN 'vanillin'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sweet aromatics') THEN 'sweet aromatics'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'jolly rancher') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bubblegum') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'agave') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cream') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nougat') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'halvah') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'praline') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'candy') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'taffy') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'marshmallow') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sugar') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sweet') THEN 'overall sweet'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'sour') THEN 'sour'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'acid') THEN 'sour'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bright') THEN 'sour'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'crisp') THEN 'sour'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tart') THEN 'sour'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'black tea') THEN 'black tea'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chamomile') THEN 'chamomile'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rose') THEN 'rose'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'jasmine') THEN 'jasmine'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'gardenia') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'freesia') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'magnolia') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'honeysuckle') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wisteria') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'verbena') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lily') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nasturtium') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lilac') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'carnation') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'narcissus') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'blossom') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'violet') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rhododendron') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hibiscus') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tea') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wisteria') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'orchid') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lantana') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'alyssum') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lavender') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'perfumed') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hyacinth') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'azalea') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'osmanthus') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chrysanthemum') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'floral') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'flower') THEN 'floral'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'bitter') THEN 'bitter'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'salty') THEN 'salty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'medicinal') THEN 'medicinal'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'petroleum') THEN 'petroleum'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'skunky') THEN 'skunky'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rubber') THEN 'rubber'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'pipe tobacco') THEN 'pipe tobacco'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tobacco') THEN 'tobacco'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'acrid') THEN 'acrid'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'burnt') THEN 'ashy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ash') THEN 'ashy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'scorched') THEN 'ashy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'smoky') THEN 'smoky'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'toasted') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'roast-toned') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'roast-prominent') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'leather') THEN 'burnt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'teriyaki sauce') THEN 'burnt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tamari') THEN 'burnt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bold') THEN 'burnt'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'stale') THEN 'stale'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cardboard') THEN 'cardboard'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'paper') THEN 'papery'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cedar') THEN 'woody'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wood') THEN 'woody'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'oak') THEN 'woody'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fir') THEN 'woody'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mesquite') THEN 'woody'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'elm') THEN 'woody'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sassafras') THEN 'woody'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'balsa') THEN 'woody'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'barley') THEN 'woody'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bay tree') THEN 'woody'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pine') THEN 'woody'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'eucalyptus') THEN 'woody'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'palo santo') THEN 'woody'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'moist') THEN 'moldy/damp'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mold') THEN 'moldy/damp'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'damp') THEN 'moldy/damp'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dusty') THEN 'musty/dusty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'petrichor') THEN 'musty/earthy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'amber') THEN 'musty/earthy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'earth') THEN 'musty/earthy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'must') THEN 'musty/earthy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'musk') THEN 'musty/earthy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cannabis') THEN 'musty/earthy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mushroom') THEN 'musty/earthy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'phenolic') THEN 'phenolic'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'animalic') THEN 'animalic'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'meat') THEN 'meaty/brothy'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'broth') THEN 'meaty/brothy'

             ELSE 'other' END AS detailed_category,

        CASE
             WHEN CONTAINS_SUBSTR(tasting_notes , 'blackberry') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mulberry') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'boysenberry') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'elderberry') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'raspberry') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'blueberry') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'gooseberry') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'strawberry') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cranberry') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'goji') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'currant') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'berry') THEN 'berry'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'berries') THEN 'berry'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'raisin') THEN 'dried fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'golden raisin') THEN 'dried fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'prune') THEN 'dried fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dried plum') THEN 'dried fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'date') THEN 'dried fruit'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'coconut') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cherry') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pomegranate') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pinapple') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grape') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'apple') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'peach') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pear') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'banana') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'juicy') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'juniper') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'persimmon') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'apricot') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'plum') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fig') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pluot') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tamarind') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rhubarb') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tomato') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'guava') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'papaya') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lychee') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'passion') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'starfruit') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mango') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'melon') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cantaloupe') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'honeydew') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'breadfruit') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'loquat') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruit-toned') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruit-forward') THEN 'other fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruity') THEN 'other fruit'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'lemon') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grapefruit') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pomelo') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'orange') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bergamot') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tangerine') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nectarine') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mandarin') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'kumquat') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lime') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'yuzu') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sumac') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'citrus') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'clementine') THEN 'citrus fruit'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'quince') THEN 'citrus fruit'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruit') THEN 'other fruit'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'rum') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grappa') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'brandy') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cognac') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'whiskey') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wine') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'yogurt') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'milk') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cheese') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pinot noir') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bourbon') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tequila') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'framboise') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cointreau') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'liqueur') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ferment') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'overripe') THEN 'alcohol/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'alcohol') THEN 'alcohol/fermented'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'olive oil') THEN 'olive oil'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'raw') THEN 'raw'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'under-ripe') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'peapod') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fresh') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dark green') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vegetable') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vegetative') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hay') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'herb') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mint') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'parsely') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'parsley') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grass') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hop') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bay leaf') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'thyme') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ginseng') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ginger') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'marjoram') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tarragon') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sarsaparilla') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'frankincense') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'frankinense') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'oregano') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fennel') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cilantro') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dill') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'herb') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'turmeric') THEN 'green/vegetative'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'bean') THEN 'beany'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'malt') THEN 'cereal'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cereal') THEN 'cereal'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grain') THEN 'cereal'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'graham cracker') THEN 'cereal'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rice') THEN 'cereal'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sage') THEN 'pungent'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pungent') THEN 'pungent'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pepper') THEN 'pepper'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'anise') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nutmeg') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mace') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cinammon') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cinnamon') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'clove') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cardamom') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'myrrh') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'myrhh') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'coriander') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cumin') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mustard') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cayenne') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'celery seed') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'paprika') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'saffron') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'spicy') THEN 'brown spice'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'spice') THEN 'brown spice'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'peanuts') THEN 'nutty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hazelnut') THEN 'nutty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'almond') THEN 'nutty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pistachio') THEN 'nutty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cashew') THEN 'nutty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pecan') THEN 'nutty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'frangipane') THEN 'nutty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'marzipan') THEN 'nutty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'macadamia') THEN 'nutty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hemp-seed') THEN 'nutty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'taro') THEN 'nutty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nut') THEN 'nutty'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'dark chocolate') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chocolate') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chocolaty') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cocoa') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cacao') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cocoo') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cocao') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'carob') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tiramisu') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fudge') THEN 'cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'oreo') THEN 'cocoa'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'molasses') THEN 'brown sugar'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'toffee') THEN 'brown sugar'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'maple syrup') THEN 'brown sugar'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'caramel') THEN 'brown sugar'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'butterscotch') THEN 'brown sugar'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'brown sugar') THEN 'brown sugar'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'creme brulee') THEN 'brown sugar'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'honey') THEN 'brown sugar'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vanilla') THEN 'vanilla'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vanillin') THEN 'vanillin'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sweet aromatics') THEN 'sweet aromatics'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'jolly rancher') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bubblegum') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'agave') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cream') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nougat') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'halvah') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'praline') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'candy') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'taffy') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'marshmallow') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sugar') THEN 'overall sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sweet') THEN 'overall sweet'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'sour') THEN 'sour'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'acid') THEN 'sour'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bright') THEN 'sour'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'crisp') THEN 'sour'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tart') THEN 'sour'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'black tea') THEN 'black tea'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chamomile') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rose') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'jasmine') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'gardenia') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'freesia') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'magnolia') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'honeysuckle') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wisteria') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'verbena') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lily') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nasturtium') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lilac') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'carnation') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'narcissus') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'blossom') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'violet') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rhododendron') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hibiscus') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tea') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wisteria') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'orchid') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lantana') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'alyssum') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lavender') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'perfumed') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hyacinth') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'azalea') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'osmanthus') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chrysanthemum') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'floral') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'flower') THEN 'floral'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'bitter') THEN 'chemical'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'salty') THEN 'chemical'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'medicinal') THEN 'chemical'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'petroleum') THEN 'chemical'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'skunky') THEN 'chemical'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rubber') THEN 'chemical'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'pipe tobacco') THEN 'pipe tobacco'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tobacco') THEN 'tobacco'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'acrid') THEN 'burnt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'burnt') THEN 'burnt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ash') THEN 'burnt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'scorched') THEN 'burnt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'smoky') THEN 'burnt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'toasted') THEN 'burnt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'roast-toned') THEN 'burnt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'roast-prominent') THEN 'burnt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'leather') THEN 'burnt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'teriyaki sauce') THEN 'burnt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tamari') THEN 'burnt'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bold') THEN 'burnt'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'stale') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cardboard') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'paper') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cedar') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wood') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'oak') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fir') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mesquite') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'elm') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sassafras') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'balsa') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'barley') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bay tree') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pine') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'eucalyptus') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'palo santo') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'moist') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mold') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'damp') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dusty') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'petrichor') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'amber') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'earth') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'must') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'musk') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cannabis') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mushroom') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'phenolic') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'animalic') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'meat') THEN 'papery/musty'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'broth') THEN 'papery/musty'

             ELSE 'other' END AS descriptive_category,

        CASE
             WHEN CONTAINS_SUBSTR(tasting_notes , 'blackberry') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mulberry') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'boysenberry') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'elderberry') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'raspberry') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'blueberry') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'gooseberry') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'strawberry') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cranberry') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'goji') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'currant') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'berry') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'berries') THEN 'fruity'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'raisin') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'golden raisin') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'prune') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dried plum') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'date') THEN 'fruity'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'coconut') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cherry') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pomegranate') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pinapple') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grape') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'apple') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'peach') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pear') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'banana') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'juicy') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'juniper') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'persimmon') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'apricot') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'plum') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fig') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pluot') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tamarind') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rhubarb') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tomato') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'guava') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'papaya') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lychee') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'passion') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'starfruit') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mango') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'melon') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cantaloupe') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'honeydew') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'breadfruit') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'loquat') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruit-toned') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruit-forward') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruity') THEN 'fruity'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'lemon') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grapefruit') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pomelo') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'orange') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bergamot') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tangerine') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nectarine') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mandarin') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'kumquat') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lime') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'yuzu') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sumac') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'citrus') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'clementine') THEN 'fruity'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'quince') THEN 'fruity'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'fruit') THEN 'fruity'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'rum') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grappa') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'brandy') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cognac') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'whiskey') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wine') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'yogurt') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'milk') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cheese') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pinot noir') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bourbon') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tequila') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'framboise') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cointreau') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'liqueur') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ferment') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'overripe') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'alcohol') THEN 'sour/fermented'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'olive oil') THEN 'green/vegetative'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'raw') THEN 'green/vegetative'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'under-ripe') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'peapod') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fresh') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dark green') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vegetable') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vegetative') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hay') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'herb') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mint') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'parsely') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'parsley') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grass') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hop') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bay leaf') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'thyme') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ginseng') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ginger') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'marjoram') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tarragon') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sarsaparilla') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'frankincense') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'frankinense') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'oregano') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fennel') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cilantro') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dill') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'herb') THEN 'green/vegetative'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'turmeric') THEN 'green/vegetative'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'bean') THEN 'green/vegetative'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'malt') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cereal') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'grain') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'graham cracker') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rice') THEN 'roasted'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sage') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pungent') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pepper') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'anise') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nutmeg') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mace') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cinammon') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cinnamon') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'clove') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cardamom') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'myrrh') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'myrhh') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'coriander') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cumin') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mustard') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cayenne') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'celery seed') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'paprika') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'saffron') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'spicy') THEN 'spices'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'spice') THEN 'spices'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'peanuts') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hazelnut') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'almond') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pistachio') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cashew') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pecan') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'frangipane') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'marzipan') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'macadamia') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hemp-seed') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'taro') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nut') THEN 'nutty/cocoa'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'dark chocolate') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chocolate') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chocolaty') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cocoa') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cacao') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cocoo') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cocao') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'carob') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tiramisu') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fudge') THEN 'nutty/cocoa'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'oreo') THEN 'nutty/cocoa'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'molasses') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'toffee') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'maple syrup') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'caramel') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'butterscotch') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'brown sugar') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'creme brulee') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'honey') THEN 'sweet'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vanilla') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'vanillin') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sweet aromatics') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'jolly rancher') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bubblegum') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'agave') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cream') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nougat') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'halvah') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'praline') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'candy') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'taffy') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'marshmallow') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sugar') THEN 'sweet'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sweet') THEN 'sweet'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'sour') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'acid') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bright') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'crisp') THEN 'sour/fermented'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tart') THEN 'sour/fermented'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'black tea') THEN 'black tea'
             
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chamomile') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rose') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'jasmine') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'gardenia') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'freesia') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'magnolia') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'honeysuckle') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wisteria') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'verbena') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lily') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'nasturtium') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lilac') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'carnation') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'narcissus') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'blossom') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'violet') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rhododendron') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hibiscus') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tea') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wisteria') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'orchid') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lantana') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'alyssum') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'lavender') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'perfumed') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'hyacinth') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'azalea') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'osmanthus') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'chrysanthemum') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'floral') THEN 'floral'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'flower') THEN 'floral'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'bitter') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'salty') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'medicinal') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'petroleum') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'skunky') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'rubber') THEN 'other'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'pipe tobacco') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tobacco') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'acrid') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'burnt') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'ash') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'scorched') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'smoky') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'toasted') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'roast-toned') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'roast-prominent') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'leather') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'teriyaki sauce') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'tamari') THEN 'roasted'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bold') THEN 'roasted'

             WHEN CONTAINS_SUBSTR(tasting_notes , 'stale') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cardboard') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'paper') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cedar') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'wood') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'oak') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'fir') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mesquite') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'elm') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'sassafras') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'balsa') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'barley') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'bay tree') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'pine') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'eucalyptus') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'palo santo') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'moist') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mold') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'damp') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'dusty') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'petrichor') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'amber') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'earth') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'must') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'musk') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'cannabis') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'mushroom') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'phenolic') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'animalic') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'meat') THEN 'other'
             WHEN CONTAINS_SUBSTR(tasting_notes , 'broth') THEN 'other'

             ELSE 'other' END AS general_category

    FROM split_temp

)

select
    coffee_id,
    REPLACE((
    REPLACE((
    REPLACE((
    REPLACE((
    REPLACE(
    LTRIM(tasting_notes), ' in aroma and cup', ''))
    , 'a hint of ', ''))
    , 'fresh-cut ', ''))
    , 'hint of ', ''))
    , '-like flowers', '')
    as tasting_notes,
    taste,
    detailed_category,
    descriptive_category,
    general_category

from categories